package main

interface ALFrameManager
	fn getMethodList() -> Vec<str> //uid:105
	fn newBehaviorFromFile(xmlFilePath: str, name: str) -> str //uid:114
	fn playBehavior(id: str) //uid:119
	fn exitBehavior(id: str) //uid:120
	fn behaviors() -> Vec<str> //uid:130

	sig behaviorPlayed(P0: str) //uid:151
	sig behaviorStopped(P0: str) //uid:152
	sig behaviorFailed(P0: str, P1: str, P2: str) //uid:154
end
